import type { Ticket } from '../../apis/exhibition';

export const FALLBACK_TICKETS: Ticket[] = [
  {
    id: 1,
    title: '숏폼 러버 MZ',
    curatorName: '트렌디 큐레이터 MZ',
    curatorMessage: '빠르게 즐기는 MZ세대 맞춤 영화',
    tags: ['트렌디', '숏폼', 'MZ'],
    ticketCode: 'shortform_mz',
    color: '#FF6B6B',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket1.png',
    characterImageUrl: '/cara/h_cara1.png',
    description: '숏폼 콘텐츠를 즐기는 MZ세대를 위한 티켓'
  },
  {
    id: 2,
    title: '영화덕후의 최애 마이너영화',
    curatorName: '인디 마니아 큐레이터',
    curatorMessage: '숨은 명작을 찾는 당신을 위한 선택',
    tags: ['인디', '마이너', '숨은명작'],
    ticketCode: 'indie_lover',
    color: '#4ECDC4',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket2.png',
    characterImageUrl: '/cara/h_cara2.png',
    description: '나만 알고 싶은 보물 같은 영화들'
  },
  {
    id: 3,
    title: '편안하고 잔잔한 감성',
    curatorName: '힐링 큐레이터',
    curatorMessage: '마음이 편안해지는 잔잔한 영화',
    tags: ['힐링', '감성', '잔잔함'],
    ticketCode: 'calm_healing',
    color: '#95E1D3',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket3.png',
    characterImageUrl: '/cara/h_cara3.png',
    description: '지친 하루 끝에 위로가 되는 영화'
  },
  {
    id: 4,
    title: '찝찝한 여운의 우울한 명작',
    curatorName: '다크 큐레이터',
    curatorMessage: '깊은 여운을 남기는 다크한 영화',
    tags: ['다크', '우울', '여운'],
    ticketCode: 'dark_masterpiece',
    color: '#2C3E50',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket4.png',
    characterImageUrl: '/cara/h_cara4.png',
    description: '생각할 거리를 던져주는 묵직한 영화'
  },
  {
    id: 5,
    title: '뇌 빼고도 볼 수 있는 레전드 코미디',
    curatorName: '코미디 큐레이터',
    curatorMessage: '웃음이 필요할 때 보는 코미디',
    tags: ['코미디', '웃음', '유쾌'],
    ticketCode: 'mindless_comedy',
    color: '#F9CA24',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket5.png',
    characterImageUrl: '/cara/h_cara5.png',
    description: '아무 생각 없이 웃고 싶을 때'
  },
  {
    id: 6,
    title: '심장 터질 것 같은 액션 범죄',
    curatorName: '액션 큐레이터',
    curatorMessage: '손에 땀을 쥐게 하는 액션 영화',
    tags: ['액션', '범죄', '스릴'],
    ticketCode: 'action_crime',
    color: '#E74C3C',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket6.png',
    characterImageUrl: '/cara/h_cara6.png',
    description: '스트레스를 날려버릴 화끈한 액션'
  },
  {
    id: 7,
    title: '세계관 과몰입 SF러버',
    curatorName: 'SF 큐레이터',
    curatorMessage: '상상력을 자극하는 SF 영화',
    tags: ['SF', '판타지', '상상력'],
    ticketCode: 'sf_fantasy',
    color: '#3498DB',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket7.png',
    characterImageUrl: '/cara/h_cara7.png',
    description: '새로운 세계로의 여행'
  },
  {
    id: 8,
    title: '이거 실화야? 실화야.',
    curatorName: '논픽션 큐레이터',
    curatorMessage: '실화를 바탕으로 한 감동의 이야기',
    tags: ['실화', '논픽션', '감동'],
    ticketCode: 'true_story',
    color: '#16A085',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket8.png',
    characterImageUrl: '/cara/h_cara8.png',
    description: '영화보다 더 영화 같은 현실 이야기'
  },
  {
    id: 9,
    title: '여름에 찰떡인 역대급 호러',
    curatorName: '호러 큐레이터',
    curatorMessage: '등골이 오싹해지는 공포 영화',
    tags: ['호러', '공포', '오싹'],
    ticketCode: 'summer_horror',
    color: '#8E44AD',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket9.png',
    characterImageUrl: '/cara/h_cara9.png',
    description: '오늘 밤 잠들 수 없는 공포'
  },
  {
    id: 10,
    title: '설레고 싶은 날의 로맨스',
    curatorName: '로맨스 큐레이터',
    curatorMessage: '가슴 설레는 로맨스 영화',
    tags: ['로맨스', '설렘', '사랑'],
    ticketCode: 'romance',
    color: '#FF69B4',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket10.png',
    characterImageUrl: '/cara/h_cara10.png',
    description: '연애 세포를 깨우는 달콤한 이야기'
  },
  {
    id: 11,
    title: '3D 보단 2D',
    curatorName: '애니메이션 큐레이터',
    curatorMessage: '감성 가득한 2D 애니메이션',
    tags: ['애니메이션', '2D', '감성'],
    ticketCode: 'animation',
    color: '#FFA07A',
    width: 300,
    height: 450,
    ticketImageUrl: '/ticket/ticket11.png',
    characterImageUrl: '/cara/h_cara11.png',
    description: '어른들을 위한 동화'
  }
];